### ISSUE TITLE
Tempest Issues with 2.01

### ISSUE THREAD

**Issue by macjeff** [bpaauwe/WeatherFlow#7]
1. Is there any way to add the Tempest as well as old Air and Sky?  I want to compare data.

2. I erased and reinstalled and put the Station ID of tempest.   The nodes came in and the one called HUB had strange stuff in it.   I restarted the node server and admin console again and same thing.  I noticed the Tempest SN had not come in but then all of a sudden it did and then the HUB node went away.  I assume this is normal?

<img width="1299" alt="Screen Shot 2020-02-26 at 9 07 58 PM" src="https://user-images.githubusercontent.com/20373758/75406313-27af3800-58de-11ea-93f9-c2b6665a63d4.png">

**Comment by bpaauwe** [comment]
The node server is designed to support only one station with one set of sensors, either an Air/Sky combo or Tempest.

I'm not sure I fully understand what you are reporting with #2.  The hub node is new and takes over some of the data that was originally displayed in the main controller node (battery voltages and signal strength) and adds a report of the actual internal sensor status.   The reason for creating a separate node for this is so I can dynamically create the node with the proper fields for an Air/Sky/Tempest. It's not possible to dynamically change the controller node fields when switching stations.

Because the hub node is created to match the fields needed for a specific station and you can switch stations, the hub node is deleted and recreated to match the currently configured station.

The serial number configuration parameters are there to allow configuration if you don't have access to the WeatherFlow servers (I.E. if your station is not connected to the Internet).

**Comment by macjeff** [comment]
I just deleted the nodeserver again.   I restarted admin console.  I then reinstalled the NodeServer, again restarted admin console.   I added my StationID (for tempest).  I watched everything come up,.  Then all the nodes came in.  One of them was Hub.  I clicked on it and it had all those OK's in all the fields like the picture which I assume should be numbers and voltage was at zero.  I watched and about 30 seconds later hub deleted itself.  Is this normal?  I checked the CONFIGURATION and it did bring in Tempest Serial, Altitude, Units, Etc.  So am I not supposed to have the hub node anymore.  My number of nodes was at 9 and goes to 8 when hub disappears.  If I change to my other station hub comes back and is fine.  So its only with the tempest that is the issue.

for the other issue I wish you could install the node twice (two slots) so I could see both stations but since NodeLink supports it, I have the old one in NodeLink and the Tempest in your node.

Let me know about the hub going away.   I can give you my station ID if you want it but would prefer to send that privately

**Comment by bpaauwe** [comment]
Ah, I understand.  No, the hub node isn't supposed to go away once the node server is started. 

The sensor status boxes are supposed to be "OK", that's good. They represent the internal physical sensors in the device and will report "FAIL" if there's a problem.    There have been some reports recently on the WeatherFlow forum of people having sensors fail so I though it might be nice to report that status in the node server where it could actually be monitored and alerts generated if something failed.  One of my Sky devices was showing the light sensor failed for a week or so, then it came back on-line has been working since then.  So that's the intent of those values in that node.

Maybe then need better names?  I thought about adding using some thing like "temperature status" but thought that might be too long to look good on the admin console.

**Comment by macjeff** [comment]
Also with the tempest.  The settings in App are for Pressure in MB, but in the node its in inHg
All other measurements are in the units I expect.

**Comment by macjeff** [comment]
And back to the original hub issue.  Yes adding STATUS to the name would make it easier to understand the OK.  

What can I do to help you figure out why my HUB node disappears.  Literally on reinstall I see 9 nodes but as soon as it starts getting info from the tempest the Hub node goes away.

UPDATE-  I rebooted the node server (For like the third time) and hub just reappeared.  This is so strange.  Its sticking now.  But yes you should add status to the names.

**Comment by macjeff** [comment]
when I went back in tonight (before the 2.02 update) the hub node was gone again.  Then I updated to 2.02.  The hub still did not come back.  Then I did a re-discover and the hub node came back.  Then I figured out how to force it to go away.  I restarted the node server again and it disappeared.   I did a rediscover and it came back

I did a video for you.  Watch the number of nodes 9 is with the hub node and 8 is without the hub node.  Otherwise 2.02 looks good.

[Screen Recording 2020-02-27 at 9.32.31 PM.zip](https://github.com/bpaauwe/WeatherFlow/files/4265031/Screen.Recording.2020-02-27.at.9.32.31.PM.zip)

**Comment by bpaauwe** [comment]
Every time the node server starts, it deletes the hub node and then re-creates it.  This is because it gets created differently depending on the station configuration. This is needed to allow switching stations.  However, I've noticed a couple of times now that Polyglot seems to fail to re-create the node. I'm not getting any errors back from the call, it just seems to silently fail. Restarting the node server again usually brings it back.

The discover command does the same thing as a restart, it will delete the node and then re-create it.

Based on your feedback I'm wondering if it is failing because something in Polyglot hasn't finished actually deleting the node and when I re-create it, it fails because the node sill exists.  Then the next discover/restart it succeeds because the node was finally fully deleted.

Time for more investigation on why Polyglot doesn't seem to work the way it should.

**Comment by macjeff** [comment]
I left it for 15 minutes and did not come back but the second I do re discover it pops in.  I also tried rebooting multiple times and yes every once and a while the reboot would bring it back but not every time.   I just checked and the hub is still there so hopefully it stays.  I do have to reboot Polisy, nodeservers, and ISY Sometimes and I don’t always look at weather flow so that could’ve been the reason it was randomly disappearing on me and definitely after restarting your Node server it disappears

**Comment by jimboca** [comment]
@bpaauwe If you delete and re-add the node on restart, then I think that will invalidate any programs that reference that node, users will have to update/save those programs.

**Comment by macjeff** [comment]
I have been lucky.  As long as the same version NodeServer is deleted and reinstalled in the same slot all my programs stayed perfect. Change slots or install and updated version of the nodeserver after the delete and you are correct.

**Comment by jimboca** [comment]
The programs will stay and look ok, but they may not evaluate their true/false status properly if you are testing a node server driver in the "if"...

**Comment by bpaauwe** [comment]
@jimboca you're right it does. But that seems to be the only way to actually update the node on the ISY. Just doing a addNode() doesn't update it.

I've made a compromise where I only delete and re-create when the station ID changes. In that case the node drivers are changing so expecting programs to work across that change isn't valid.  The new version will delete and re-create the first time it is run, but all subsequent restarts and discover calls shouldn't cause it to be deleted.

**Comment by macjeff** [comment]
the latest version 2.03 is better.  It disappeared and then came right back almost instantly.  I also watched nodes go from 9 to 8 to 9 within seconds.   I guess we can close this but I will leave that to you since Jimbo is in this also.
